steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$SHORT_SHA'
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$SHORT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - images
      - add-tag
      - $_IMAGE_NAME:$SHORT_SHA
      - $_IMAGE_NAME:latest
    id: adding the 'latest' tag for the image
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: 'bash'
    args:
      - '-c'
      - >
        gcloud deploy releases create release-$BUILD_ID
        --delivery-pipeline=my-gke-demo-app-1
        --region=$_GKE_LOCATION
        --source=./
        --images=_K8S_APP_NAME=$_IMAGE_NAME:$SHORT_SHA
images:
  - '$_IMAGE_NAME:$SHORT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_ANNOTATIONS: gcb-trigger-id=739d8e78-595c-45f8-96a7-536496685cb5
  _K8S_LABELS: ''
  _GKE_CLUSTER: gke-cluster-dev
  _K8S_YAML_PATH: kubernetes/
  _IMAGE_NAME: gcr.io/cube-render-farm/github.com/dariobernardo/simple_app
  _GKE_LOCATION: europe-west3
  _OUTPUT_BUCKET_PATH: cube-render-farm_cloudbuild/deploy
  _K8S_APP_NAME: simple-app
  _K8S_NAMESPACE: default
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
