steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$SHORT_SHA'
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$SHORT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - images
      - add-tag
      - $_IMAGE_NAME:$SHORT_SHA
      - $_IMAGE_NAME:latest
    id: adding the 'latest' tag for the image
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: 'bash'
    args:
      - '-c'
      - >
        gcloud deploy releases create release-$BUILD_ID
        --delivery-pipeline=$_CLUSTER_NAME_PREFIX-deploy-pipeline
        --project=$PROJECT_ID
        --region=$_REGION
        --source=./
        --images=_APP_NAME=$_IMAGE_NAME:$SHORT_SHA
images:
  - '$_IMAGE_NAME:$SHORT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _IMAGE_NAME: gcr.io/$PROJECT_ID/simple-app
  _REGION: europe-west3
  _APP_NAME: simple-app
  _CLUSTER_NAME_PREFIX: gke-cluster
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
