apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  selector:
    app: simple-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: gcr.io/cube-render-farm/github.com/dariobernardo/simple_app
        ports:
        - containerPort: 8080